config/routes.rb
Rails.application.routes.draw do

  get 'favorites/toggle'
  root to: 'comic_collections#index'

  resources :comic_collections, only: :index

  get 'search_character', to: 'characters#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/marvel_api.rb
class MarvelApi

  HOST = "gateway.marvel.com"
  PUBLIC_KEY = Rails.application.credentials.marvel_public_key
  PRIVATE_KEY = Rails.application.credentials.marvel_private_key

  attr_reader :response, :body, :data, :results

  def initialize(endpoint = '')
    @endpoint = "/v1/public/" + endpoint
    ts = Time.now.to_i.to_s
    hash_value = Digest::MD5.hexdigest ts + PRIVATE_KEY + PUBLIC_KEY
    @authentication_query_string = "ts=#{Time.now.to_i}&apikey=#{PUBLIC_KEY}&hash=#{hash_value}"
  end

  def request
    @response ||= Net::HTTP.get_response(uri)
    @body = JSON.parse(@response.body)
    @data = @body["data"]
    @results = @data["results"]
  end

  private
    def uri
      URI::HTTPS.build(host: HOST, path: @endpoint, query: @authentication_query_string)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cookie

  def set_cookie
    unless cookies[:current_user]
      cookies[:current_user] = { value: Time.current, expires: 30.minutes }
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def search
    if params["character_name"] != ""
      character = Character.new params["character_name"]
      redirect_to comic_collections_path(character: character.id, character_name: params["character_name"])
    else
      redirect_to comic_collections_path
    end
  end
end

app/controllers/comic_collections_controller.rb
class ComicCollectionsController < ApplicationController

  def index
    @character = params["character"]
    @character_name = params["character_name"]

    comic_colection = ComicCollection.new offset: params["offset"].to_i, characters: @character
    @previous_offset = [0, comic_colection.offset.to_i - comic_colection.limit.to_i].max
    @next_offset = [comic_colection.offset.to_i + comic_colection.limit.to_i, comic_colection.total.to_i].min
    @comics = comic_colection.comics
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def toggle
    if favorite = Favorite.find_by(comic_id: params["comic_id"], user_session: cookies[:current_user])
      favorite.destroy
    else
      Favorite.create comic_id: params["comic_id"], user_session: cookies[:current_user]
    end
    render partial: "comic_collections/comic_cover", locals: {comic: Comic.new(params["comic_id"])}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comic_collections/_comic_cover.erb
<%=image_tag comic.cover_url, size: "300x400", alt: comic.id, class: 'cover', data: {action: "click->comics#toggleFavorite"} %>

<%=image_tag "heart_hover.png", alt: 'heart_hover', class: "heart" %>
<%=image_tag "heart_off.png", alt: 'heart_off', class: "heart-off" %>
<% if comic.favorite(cookies[:current_user]) then %>
  <%=image_tag "heart_on.png", alt: 'heart_on', class: "heart-on" %>
<% end %>

app/views/comic_collections/index.erb
<div class="flex-column" style="background-color: red; align-items: center; justify-content: center;">
  <%=link_to image_tag('marvel_logo.png', alt: 'Marvel show room'), root_path %>
  <div style= "padding: 50px">
    <%=form_with url: search_character_path, method: :get do |f| %>
      <%= f.text_field 'character_name', placeholder: 'Find by character', value: @character_name %>
      <%= f.submit "Search" %>
    <% end %>
  </div>
</div>

<div class="flex-row">
  <%-@comics.each do |comic| %>
    <%-if comic.cover_url.present? %>
      <div class="cover-wrapper" data-controller="comics" data-comics-url-value=<%=favorites_toggle_path(comic_id: comic.id) %>>
        <%=render "comic_cover", comic: comic%>
      </div>
    <% end %>
  <% end %>
</div>
<div class="flex-row navigation-buttons">
    <%=link_to comic_collections_path(offset: @previous_offset, character: @character, character_name: @character_name) do%>
      <button class= "btn navigation-button">
        PREVIOUS
      </button>
    <% end %>
    <%=link_to comic_collections_path(offset: @next_offset, character: @character, character_name: @character_name) do%>
      <button class="btn navigation-button">
        NEXT
      </button>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>